// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA753ZXCbA3gJjjUb2bjjUX7FuDXCgbl7A',
    appId: '1:823402662482:ios:536a2d99e4cadbabaa6d8b',
    messagingSenderId: '823402662482',
    projectId: 'cetisafe-137a7',
    storageBucket: 'cetisafe-137a7.firebasestorage.app',
    iosClientId: '823402662482-g2iiv8bma4jjrmhjrkb1taudbrtt99k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cetisafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA753ZXCbA3gJjjUb2bjjUX7FuDXCgbl7A',
    appId: '1:823402662482:ios:536a2d99e4cadbabaa6d8b',
    messagingSenderId: '823402662482',
    projectId: 'cetisafe-137a7',
    storageBucket: 'cetisafe-137a7.firebasestorage.app',
    iosClientId: '823402662482-g2iiv8bma4jjrmhjrkb1taudbrtt99k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cetisafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAliT2-32-VeTasif4am0RR9jh7AO2wrC0',
    appId: '1:823402662482:web:e013f3c81af50799aa6d8b',
    messagingSenderId: '823402662482',
    projectId: 'cetisafe-137a7',
    authDomain: 'cetisafe-137a7.firebaseapp.com',
    storageBucket: 'cetisafe-137a7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAliT2-32-VeTasif4am0RR9jh7AO2wrC0',
    appId: '1:823402662482:web:15bc7ca3d8cc37a7aa6d8b',
    messagingSenderId: '823402662482',
    projectId: 'cetisafe-137a7',
    authDomain: 'cetisafe-137a7.firebaseapp.com',
    storageBucket: 'cetisafe-137a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh9T3VmBKCQmumFdFtbqLzT7YKa6Mufwo',
    appId: '1:823402662482:android:c984185a00331f15aa6d8b',
    messagingSenderId: '823402662482',
    projectId: 'cetisafe-137a7',
    storageBucket: 'cetisafe-137a7.firebasestorage.app',
  );

}